//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright metal-stack Authors.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfiguration) DeepCopyInto(out *ControllerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.SynologyConfig.DeepCopyInto(&out.SynologyConfig)
	if in.HealthCheckConfig != nil {
		in, out := &in.HealthCheckConfig, &out.HealthCheckConfig
		*out = new(configv1alpha1.HealthCheckConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfiguration.
func (in *ControllerConfiguration) DeepCopy() *ControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIStorageClass) DeepCopyInto(out *ISCSIStorageClass) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIStorageClass.
func (in *ISCSIStorageClass) DeepCopy() *ISCSIStorageClass {
	if in == nil {
		return nil
	}
	out := new(ISCSIStorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynologyConfiguration) DeepCopyInto(out *SynologyConfiguration) {
	*out = *in
	in.StorageClasses.DeepCopyInto(&out.StorageClasses)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynologyConfiguration.
func (in *SynologyConfiguration) DeepCopy() *SynologyConfiguration {
	if in == nil {
		return nil
	}
	out := new(SynologyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynologyStorageClasses) DeepCopyInto(out *SynologyStorageClasses) {
	*out = *in
	in.ISCSI.DeepCopyInto(&out.ISCSI)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynologyStorageClasses.
func (in *SynologyStorageClasses) DeepCopy() *SynologyStorageClasses {
	if in == nil {
		return nil
	}
	out := new(SynologyStorageClasses)
	in.DeepCopyInto(out)
	return out
}
