//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	config "github.com/metal-stack/gardener-extension-csi-driver-synology/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ISCSIStorageClass)(nil), (*config.ISCSIStorageClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ISCSIStorageClass_To_config_ISCSIStorageClass(a.(*ISCSIStorageClass), b.(*config.ISCSIStorageClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ISCSIStorageClass)(nil), (*ISCSIStorageClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ISCSIStorageClass_To_v1alpha1_ISCSIStorageClass(a.(*config.ISCSIStorageClass), b.(*ISCSIStorageClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SynologyConfiguration)(nil), (*config.SynologyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SynologyConfiguration_To_config_SynologyConfiguration(a.(*SynologyConfiguration), b.(*config.SynologyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SynologyConfiguration)(nil), (*SynologyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SynologyConfiguration_To_v1alpha1_SynologyConfiguration(a.(*config.SynologyConfiguration), b.(*SynologyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SynologyStorageClasses)(nil), (*config.SynologyStorageClasses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SynologyStorageClasses_To_config_SynologyStorageClasses(a.(*SynologyStorageClasses), b.(*config.SynologyStorageClasses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SynologyStorageClasses)(nil), (*SynologyStorageClasses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SynologyStorageClasses_To_v1alpha1_SynologyStorageClasses(a.(*config.SynologyStorageClasses), b.(*SynologyStorageClasses), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	if err := Convert_v1alpha1_SynologyConfiguration_To_config_SynologyConfiguration(&in.SynologyConfig, &out.SynologyConfig, s); err != nil {
		return err
	}
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	if err := Convert_config_SynologyConfiguration_To_v1alpha1_SynologyConfiguration(&in.SynologyConfig, &out.SynologyConfig, s); err != nil {
		return err
	}
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ISCSIStorageClass_To_config_ISCSIStorageClass(in *ISCSIStorageClass, out *config.ISCSIStorageClass, s conversion.Scope) error {
	out.Parameters = *(*map[string]string)(unsafe.Pointer(&in.Parameters))
	return nil
}

// Convert_v1alpha1_ISCSIStorageClass_To_config_ISCSIStorageClass is an autogenerated conversion function.
func Convert_v1alpha1_ISCSIStorageClass_To_config_ISCSIStorageClass(in *ISCSIStorageClass, out *config.ISCSIStorageClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_ISCSIStorageClass_To_config_ISCSIStorageClass(in, out, s)
}

func autoConvert_config_ISCSIStorageClass_To_v1alpha1_ISCSIStorageClass(in *config.ISCSIStorageClass, out *ISCSIStorageClass, s conversion.Scope) error {
	out.Parameters = *(*map[string]string)(unsafe.Pointer(&in.Parameters))
	return nil
}

// Convert_config_ISCSIStorageClass_To_v1alpha1_ISCSIStorageClass is an autogenerated conversion function.
func Convert_config_ISCSIStorageClass_To_v1alpha1_ISCSIStorageClass(in *config.ISCSIStorageClass, out *ISCSIStorageClass, s conversion.Scope) error {
	return autoConvert_config_ISCSIStorageClass_To_v1alpha1_ISCSIStorageClass(in, out, s)
}

func autoConvert_v1alpha1_SynologyConfiguration_To_config_SynologyConfiguration(in *SynologyConfiguration, out *config.SynologyConfiguration, s conversion.Scope) error {
	out.URL = in.URL
	out.SecretRef = in.SecretRef
	if err := Convert_v1alpha1_SynologyStorageClasses_To_config_SynologyStorageClasses(&in.StorageClasses, &out.StorageClasses, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SynologyConfiguration_To_config_SynologyConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_SynologyConfiguration_To_config_SynologyConfiguration(in *SynologyConfiguration, out *config.SynologyConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_SynologyConfiguration_To_config_SynologyConfiguration(in, out, s)
}

func autoConvert_config_SynologyConfiguration_To_v1alpha1_SynologyConfiguration(in *config.SynologyConfiguration, out *SynologyConfiguration, s conversion.Scope) error {
	out.URL = in.URL
	out.SecretRef = in.SecretRef
	if err := Convert_config_SynologyStorageClasses_To_v1alpha1_SynologyStorageClasses(&in.StorageClasses, &out.StorageClasses, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_SynologyConfiguration_To_v1alpha1_SynologyConfiguration is an autogenerated conversion function.
func Convert_config_SynologyConfiguration_To_v1alpha1_SynologyConfiguration(in *config.SynologyConfiguration, out *SynologyConfiguration, s conversion.Scope) error {
	return autoConvert_config_SynologyConfiguration_To_v1alpha1_SynologyConfiguration(in, out, s)
}

func autoConvert_v1alpha1_SynologyStorageClasses_To_config_SynologyStorageClasses(in *SynologyStorageClasses, out *config.SynologyStorageClasses, s conversion.Scope) error {
	if err := Convert_v1alpha1_ISCSIStorageClass_To_config_ISCSIStorageClass(&in.ISCSI, &out.ISCSI, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SynologyStorageClasses_To_config_SynologyStorageClasses is an autogenerated conversion function.
func Convert_v1alpha1_SynologyStorageClasses_To_config_SynologyStorageClasses(in *SynologyStorageClasses, out *config.SynologyStorageClasses, s conversion.Scope) error {
	return autoConvert_v1alpha1_SynologyStorageClasses_To_config_SynologyStorageClasses(in, out, s)
}

func autoConvert_config_SynologyStorageClasses_To_v1alpha1_SynologyStorageClasses(in *config.SynologyStorageClasses, out *SynologyStorageClasses, s conversion.Scope) error {
	if err := Convert_config_ISCSIStorageClass_To_v1alpha1_ISCSIStorageClass(&in.ISCSI, &out.ISCSI, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_SynologyStorageClasses_To_v1alpha1_SynologyStorageClasses is an autogenerated conversion function.
func Convert_config_SynologyStorageClasses_To_v1alpha1_SynologyStorageClasses(in *config.SynologyStorageClasses, out *SynologyStorageClasses, s conversion.Scope) error {
	return autoConvert_config_SynologyStorageClasses_To_v1alpha1_SynologyStorageClasses(in, out, s)
}
