//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	csidriversynology "github.com/metal-stack/gardener-extension-csi-driver-synology/pkg/apis/csidriversynology"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ShootConfiguration)(nil), (*csidriversynology.ShootConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootConfiguration_To_csidriversynology_ShootConfiguration(a.(*ShootConfiguration), b.(*csidriversynology.ShootConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*csidriversynology.ShootConfiguration)(nil), (*ShootConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_csidriversynology_ShootConfiguration_To_v1alpha1_ShootConfiguration(a.(*csidriversynology.ShootConfiguration), b.(*ShootConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ShootConfiguration_To_csidriversynology_ShootConfiguration(in *ShootConfiguration, out *csidriversynology.ShootConfiguration, s conversion.Scope) error {
	out.SynologyURL = in.SynologyURL
	out.ChapEnabled = in.ChapEnabled
	out.Username = in.Username
	out.Password = in.Password
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_ShootConfiguration_To_csidriversynology_ShootConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootConfiguration_To_csidriversynology_ShootConfiguration(in *ShootConfiguration, out *csidriversynology.ShootConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootConfiguration_To_csidriversynology_ShootConfiguration(in, out, s)
}

func autoConvert_csidriversynology_ShootConfiguration_To_v1alpha1_ShootConfiguration(in *csidriversynology.ShootConfiguration, out *ShootConfiguration, s conversion.Scope) error {
	out.SynologyURL = in.SynologyURL
	out.ChapEnabled = in.ChapEnabled
	out.Username = in.Username
	out.Password = in.Password
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_csidriversynology_ShootConfiguration_To_v1alpha1_ShootConfiguration is an autogenerated conversion function.
func Convert_csidriversynology_ShootConfiguration_To_v1alpha1_ShootConfiguration(in *csidriversynology.ShootConfiguration, out *ShootConfiguration, s conversion.Scope) error {
	return autoConvert_csidriversynology_ShootConfiguration_To_v1alpha1_ShootConfiguration(in, out, s)
}
