//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	csidriversynology "github.com/metal-stack/gardener-extension-csi-driver-synology/pkg/apis/csidriversynology"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CsiDriverSynologyConfig)(nil), (*csidriversynology.CsiDriverSynologyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CsiDriverSynologyConfig_To_csidriversynology_CsiDriverSynologyConfig(a.(*CsiDriverSynologyConfig), b.(*csidriversynology.CsiDriverSynologyConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*csidriversynology.CsiDriverSynologyConfig)(nil), (*CsiDriverSynologyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_csidriversynology_CsiDriverSynologyConfig_To_v1alpha1_CsiDriverSynologyConfig(a.(*csidriversynology.CsiDriverSynologyConfig), b.(*CsiDriverSynologyConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CsiDriverSynologyConfig_To_csidriversynology_CsiDriverSynologyConfig(in *CsiDriverSynologyConfig, out *csidriversynology.CsiDriverSynologyConfig, s conversion.Scope) error {
	out.SynologyURL = in.SynologyURL
	out.ChapEnabled = in.ChapEnabled
	out.Username = in.Username
	out.Password = in.Password
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_CsiDriverSynologyConfig_To_csidriversynology_CsiDriverSynologyConfig is an autogenerated conversion function.
func Convert_v1alpha1_CsiDriverSynologyConfig_To_csidriversynology_CsiDriverSynologyConfig(in *CsiDriverSynologyConfig, out *csidriversynology.CsiDriverSynologyConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CsiDriverSynologyConfig_To_csidriversynology_CsiDriverSynologyConfig(in, out, s)
}

func autoConvert_csidriversynology_CsiDriverSynologyConfig_To_v1alpha1_CsiDriverSynologyConfig(in *csidriversynology.CsiDriverSynologyConfig, out *CsiDriverSynologyConfig, s conversion.Scope) error {
	out.SynologyURL = in.SynologyURL
	out.ChapEnabled = in.ChapEnabled
	out.Username = in.Username
	out.Password = in.Password
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_csidriversynology_CsiDriverSynologyConfig_To_v1alpha1_CsiDriverSynologyConfig is an autogenerated conversion function.
func Convert_csidriversynology_CsiDriverSynologyConfig_To_v1alpha1_CsiDriverSynologyConfig(in *csidriversynology.CsiDriverSynologyConfig, out *CsiDriverSynologyConfig, s conversion.Scope) error {
	return autoConvert_csidriversynology_CsiDriverSynologyConfig_To_v1alpha1_CsiDriverSynologyConfig(in, out, s)
}
